import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';

export async function generatePDFReceipt(receiptData, Print, Sharing, addToast) {
  if (!receiptData) return;

  const htmlContent = `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #0F172A; }
          .header { background: #A855F7; color: white; padding: 40px; border-radius: 20px; text-align: center; }
          .logo { font-size: 40px; font-weight: 900; margin-bottom: 10px; }
          .receipt-id { opacity: 0.8; font-size: 14px; }
          .content { margin-top: 40px; }
          .row { display: flex; justify-content: space-between; margin-bottom: 20px; border-bottom: 1px dashed #E2E8F0; padding-bottom: 10px; }
          .label { color: #64748B; font-size: 12px; text-transform: uppercase; margin-bottom: 5px; }
          .value { font-size: 18px; font-weight: 700; }
          .footer { margin-top: 60px; text-align: center; color: #94A3B8; font-size: 12px; }
          .price-box { background: #F8FAFC; padding: 20px; border-radius: 12px; margin-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">YAQEEN</div>
          <div class="receipt-id">Booking Receipt: ${receiptData.id}</div>
        </div>
        <div class="content">
          <div class="row">
            <div style="flex: 1;">
              <div class="label">Service Provider</div>
              <div class="value">${receiptData.providerName}</div>
            </div>
            <div style="flex: 1; text-align: right;">
              <div class="label">Provider ID</div>
              <div class="value" style="color: #A855F7;">${receiptData.providerID}</div>
            </div>
          </div>
          <div class="row">
            <div>
              <div class="label">Provider Address</div>
              <div class="value" style="font-size: 14px;">${receiptData.providerAddress}</div>
            </div>
          </div>
          <div style="display: flex; gap: 40px;">
            <div style="flex: 1;">
              <div class="label">Scheduled Time</div>
              <div class="value">${receiptData.time}</div>
            </div>
            <div style="flex: 1;">
              <div class="label">Service Type</div>
              <div class="value">${receiptData.service}</div>
            </div>
          </div>
          <div class="price-box">
            <div style="display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px;">
              <span>Service Charges (Agreed)</span>
              <b>Rs. ${receiptData.price}</b>
            </div>
            <div style="display: flex; justify-content: space-between; margin-bottom: 8px; font-size: 14px;">
              <span>Visiting Charges</span>
              <b>Rs. ${receiptData.visitingCharges}</b>
            </div>
            <div style="display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 14px;">
              <span>Platform Fee (10%)</span>
              <span>Rs. ${Math.round(receiptData.price * 0.1)}</span>
            </div>
            <div style="height: 1px; background: #CBD5E1; margin: 10px 0;"></div>
            <div style="display: flex; justify-content: space-between; font-size: 18px; font-weight: 900; color: #A855F7;">
              <span>TOTAL AMOUNT</span>
              <span>Rs. ${receiptData.price + receiptData.visitingCharges + Math.round(receiptData.price * 0.1)}</span>
            </div>
          </div>
        </div>
        <div class="footer">
          Generated by Yaqeen AI Orchestrator • Islamabad, Pakistan
        </div>
      </body>
    </html>
  `;

  // Make human-understandable name
  const cleanService = (receiptData.service || 'Service').replace(/[^a-zA-Z0-9]/g, '_');
  const cleanProvider = (receiptData.providerName || 'Provider').replace(/[^a-zA-Z0-9]/g, '_');
  const humanFriendlyName = `Yaqeen_Invoice_${cleanService}_${cleanProvider}.pdf`;

  try {
    addToast("Generating PDF...", 'info');
    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    if (Platform.OS === 'web') {
      const link = document.createElement('a');
      link.href = uri;
      link.download = humanFriendlyName;
      link.click();
    } else {
      // Copy to cacheDirectory with human friendly filename before sharing
      const customUri = FileSystem.cacheDirectory + humanFriendlyName;
      await FileSystem.copyAsync({
        from: uri,
        to: customUri
      });
      await Sharing.shareAsync(customUri, { UTI: '.pdf', mimeType: 'application/pdf' });
    }
    addToast("Receipt Ready!", 'success');
  } catch (error) {
    console.error("Receipt generation failed", error);
    addToast("PDF Generation Failed", 'error');
  }
}
