import { StyleSheet, Platform } from 'react-native';

// ─── Color Palettes ──────────────────────────────────────────────────────────

export const THEMES = {
  dark: {
    background: '#0D0D0D',
    nav: '#000000',
    textPrimary: '#FFFFFF',
    textSecondary: '#A1A1AA',
    primary: '#A855F7',
    danger: '#EF4444',
    card: '#1A1A1A',
    border: '#333333',
    overlay: 'rgba(0,0,0,0.8)',
    input: '#111111',
    sidebar: '#050505',
    tabActive: 'rgba(168, 85, 247, 0.15)',
    warning: '#F59E0B',
    success: '#10B981',
  },
  light: {
    background: '#F1F5F9',
    nav: '#FFFFFF',
    textPrimary: '#0F172A',
    textSecondary: '#64748B',
    primary: '#A855F7',
    danger: '#EF4444',
    card: '#FFFFFF',
    border: '#E2E8F0',
    overlay: 'rgba(0,0,0,0.5)',
    input: '#F8FAFC',
    sidebar: '#F8FAFC',
    tabActive: 'rgba(168, 85, 247, 0.1)',
    warning: '#F59E0B',
    success: '#10B981',
  },
};

// ─── Dark Map Style ───────────────────────────────────────────────────────────

export const darkMapStyle = [
  { elementType: 'geometry', stylers: [{ color: '#242f3e' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#242f3e' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#746855' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#d59563' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#d59563' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#263c3f' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#6b9a76' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#38414e' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#212a37' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#9ca5b3' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#746855' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#1f2827' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#f3d19c' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#17263c' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#515c6d' }] },
  { featureType: 'water', elementType: 'labels.text.stroke', stylers: [{ color: '#17263c' }] },
];

// ─── Shadow Helper ────────────────────────────────────────────────────────────

export const getShadow = (color, x, y, opacity, radius, elevation) => {
  if (Platform.OS === 'web') {
    let rgb = '0,0,0';
    if (color && color.startsWith('#')) {
      const hex = color.replace('#', '');
      const r = parseInt(hex.substring(0, 2), 16) || 0;
      const g = parseInt(hex.substring(2, 4), 16) || 0;
      const b = parseInt(hex.substring(4, 6), 16) || 0;
      rgb = `${r},${g},${b}`;
    } else if (color === 'purple' || color === 'violet') {
      rgb = '124,58,237';
    }
    return { boxShadow: `${x}px ${y}px ${radius}px rgba(${rgb}, ${opacity})` };
  }
  return {
    shadowColor: color,
    shadowOffset: { width: x, height: y },
    shadowOpacity: opacity,
    shadowRadius: radius,
    elevation,
  };
};

// ─── Dynamic StyleSheet ───────────────────────────────────────────────────────

export const getStyles = (COLORS) =>
  StyleSheet.create({
    authContainer: {
      flex: 1,
      backgroundColor: COLORS.background,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    authCard: {
      backgroundColor: COLORS.card,
      borderRadius: 24,
      padding: 32,
      width: '100%',
      maxWidth: 400,
      ...getShadow('#000', 0, 8, 0.15, 12, 8),
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    container: { flex: 1, backgroundColor: COLORS.background, paddingTop: 0 },
    header: {
      backgroundColor: COLORS.nav,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingTop: Platform.OS === 'web' ? 16 : Platform.OS === 'ios' ? 48 : 36,
      paddingBottom: 14,
      borderBottomLeftRadius: 0,
      borderBottomRightRadius: 0,
      width: '100%',
      maxWidth: 600,
      alignSelf: 'center',
      ...getShadow('#000', 0, 4, 0.1, 8, 4),
      zIndex: 10,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
    },
    headerTitle: { fontSize: 24, fontWeight: '900', color: COLORS.textPrimary },
    headerSubtitle: { fontSize: 14, color: COLORS.textSecondary, marginTop: 2, fontWeight: '600' },
    title: { fontSize: 26, fontWeight: '900', color: COLORS.textPrimary, marginBottom: 4, textAlign: 'center' },
    subtitle: { fontSize: 14, color: COLORS.textSecondary, marginBottom: 32, fontWeight: '600', textAlign: 'center' },
    content: { flex: 1, padding: 20, width: '100%', maxWidth: 600, alignSelf: 'center' },
    card: {
      backgroundColor: COLORS.card,
      borderRadius: 20,
      padding: 20,
      marginBottom: 20,
      ...getShadow('#000', 0, 4, 0.05, 10, 2),
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    input: {
      backgroundColor: COLORS.input,
      borderRadius: 14,
      padding: 16,
      color: COLORS.textPrimary,
      fontSize: 15,
      borderWidth: 1,
      borderColor: COLORS.border,
      marginBottom: 16,
      fontWeight: '600',
    },
    button: {
      backgroundColor: COLORS.primary,
      borderRadius: 14,
      padding: 16,
      alignItems: 'center',
      marginTop: 4,
      ...getShadow(COLORS.primary, 0, 4, 0.3, 6, 4),
    },
    secondaryButton: {
      backgroundColor: COLORS.card,
      borderRadius: 14,
      padding: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    dangerButton: { backgroundColor: COLORS.danger, borderRadius: 14, padding: 16, alignItems: 'center' },
    buttonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
    secondaryButtonText: { color: COLORS.textPrimary, fontSize: 16, fontWeight: '700' },
    logoutBtn: {
      backgroundColor: 'rgba(168, 85, 247, 0.05)',
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(168, 85, 247, 0.2)',
    },
    logoutText: { color: COLORS.primary, fontSize: 13, fontWeight: '700' },
    toggleBtn: {
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      alignItems: 'center',
      marginBottom: 16,
      backgroundColor: COLORS.input,
    },
    toggleBtnActive: { borderColor: COLORS.primary, backgroundColor: 'rgba(168, 85, 247, 0.1)' },
    toggleText: { color: COLORS.textSecondary, fontWeight: '600', fontSize: 14 },
    toggleTextActive: { color: COLORS.primary },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      alignSelf: 'center',
      width: '100%',
      maxWidth: 600,
      height: 96,
      backgroundColor: COLORS.nav,
      flexDirection: 'row',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      ...getShadow('#000', 0, -4, 0.05, 10, 10),
      paddingBottom: 28,
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 12 },
    navItemActive: { opacity: 1 },
    navText: { color: COLORS.textSecondary, fontSize: 12, fontWeight: '600', marginTop: 4 },
    navTextActive: { color: COLORS.primary, fontWeight: '800' },
    modalOverlay: { flex: 1, backgroundColor: COLORS.overlay, justifyContent: 'center', alignItems: 'center', padding: 24 },
    modalCard: {
      backgroundColor: COLORS.card,
      borderRadius: 24,
      padding: 24,
      width: '100%',
      maxWidth: 400,
      ...getShadow('#000', 0, 10, 0.1, 15, 10),
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    modalTitle: { fontSize: 20, fontWeight: '800', color: COLORS.textPrimary, marginBottom: 8 },
    modalMessage: { fontSize: 15, color: COLORS.textSecondary, marginBottom: 24, lineHeight: 22, fontWeight: '500' },
    modalButtons: { flexDirection: 'row', justifyContent: 'flex-end' },
    label: { fontSize: 15, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 12 },
    sectionTitle: { fontSize: 18, fontWeight: '800', color: COLORS.textPrimary, marginBottom: 16 },
    infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
    infoLabel: { fontSize: 14, color: COLORS.textSecondary, fontWeight: '600' },
    infoValue: { fontSize: 14, flex: 1, textAlign: 'right', color: COLORS.textPrimary, fontWeight: '700' },
    reasoningBox: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: COLORS.border },
    reasoningTitle: { fontSize: 13, color: COLORS.primary, fontWeight: '700', marginBottom: 6 },
    reasoningText: { fontSize: 13, color: COLORS.textSecondary, lineHeight: 20, fontStyle: 'italic' },
    followUpBox: {
      marginTop: 16,
      backgroundColor: 'rgba(168, 85, 247, 0.05)',
      padding: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(168, 85, 247, 0.2)',
    },
    followUpTitle: { fontSize: 12, color: COLORS.primary, fontWeight: '800', marginBottom: 4 },
    followUpText: { fontSize: 13, color: COLORS.textSecondary, fontWeight: '500' },
    errorCard: {
      backgroundColor: 'rgba(239, 68, 68, 0.05)',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      borderLeftWidth: 4,
      borderLeftColor: COLORS.danger,
    },
    successCard: {
      backgroundColor: 'rgba(16, 185, 129, 0.05)',
      borderRadius: 12,
      padding: 16,
      marginBottom: 20,
      borderLeftWidth: 4,
      borderLeftColor: '#10B981',
    },
    successText: { color: '#10B981', fontWeight: '600' },
    errorTextAuth: { color: COLORS.danger, fontWeight: '600', marginBottom: 16, textAlign: 'center' },
    errorText: { color: COLORS.danger, fontWeight: '600' },
    filterBtn: { flex: 1, padding: 12, alignItems: 'center', borderBottomWidth: 2, borderBottomColor: COLORS.border },
    filterBtnActive: { borderBottomColor: COLORS.primary },
    filterText: { fontWeight: '600', color: COLORS.textSecondary },
    filterTextActive: { color: COLORS.primary, fontWeight: '800' },
    googleButton: {
      backgroundColor: COLORS.card,
      borderRadius: 14,
      padding: 16,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    googleButtonText: { color: COLORS.textPrimary, fontSize: 15, fontWeight: '700' },
    switchButton: { marginTop: 20, alignItems: 'center' },
    switchButtonText: { color: COLORS.primary, fontWeight: '700', fontSize: 14 },
    // Settings
    settingsWrapper: {
      flexDirection: 'column',
      backgroundColor: COLORS.background,
      minHeight: 500,
      borderRadius: 24,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: COLORS.border,
      marginHorizontal: 16,
      marginTop: 8,
      width: '100%',
      maxWidth: 600,
      alignSelf: 'center',
    },
    settingsTopNav: { backgroundColor: COLORS.sidebar, padding: 20, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    sidebarTitle: { fontSize: 22, fontWeight: '900', color: COLORS.textPrimary },
    sidebarItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 12, borderRadius: 12, marginBottom: 4 },
    sidebarItemActive: { backgroundColor: COLORS.tabActive },
    sidebarText: { marginLeft: 12, fontSize: 14, fontWeight: '700', color: COLORS.textSecondary },
    sidebarTextActive: { color: COLORS.primary, fontWeight: '800' },
    settingsContent: { flex: 1, padding: 24, backgroundColor: COLORS.card },
    contentTitle: { fontSize: 24, fontWeight: '900', color: COLORS.textPrimary, marginBottom: 4 },
    contentSubtitle: { fontSize: 14, color: COLORS.textSecondary, fontWeight: '600', opacity: 0.8 },
    closeBtn: { backgroundColor: COLORS.background, padding: 8, borderRadius: 100, borderWidth: 1, borderColor: COLORS.border },
    inputLabel: { fontSize: 13, fontWeight: '800', color: COLORS.textPrimary, marginBottom: 10, marginTop: 20 },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.input,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: COLORS.border,
      paddingHorizontal: 16,
    },
    inputIcon: { marginRight: 12, opacity: 0.6 },
    compactInput: { flex: 1, height: 48, color: COLORS.textPrimary, fontSize: 14, fontWeight: '600' },
    // Danger Zone
    dangerBox: {
      backgroundColor: COLORS.input,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: 'rgba(239, 68, 68, 0.2)',
      padding: 24,
    },
    dangerHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    warningIconCircle: {
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      width: 44,
      height: 44,
      borderRadius: 22,
      justifyContent: 'center',
      alignItems: 'center',
    },
    dangerTitle: { fontSize: 18, fontWeight: '800', color: COLORS.danger, marginBottom: 4 },
    dangerDesc: { fontSize: 13, color: COLORS.textSecondary, fontWeight: '600' },
    bulletList: { marginBottom: 24, paddingLeft: 4 },
    bulletItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
    bulletDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: COLORS.textSecondary, marginRight: 12, opacity: 0.6 },
    bulletText: { fontSize: 13, color: COLORS.textSecondary, fontWeight: '600' },
    // Broadcast / Provider
    broadcastCard: {
      backgroundColor: COLORS.card,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      ...getShadow('#000', 0, 4, 0.05, 8, 3),
    },
    broadcastType: { fontSize: 16, fontWeight: '800', color: COLORS.textPrimary },
    broadcastTime: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2, fontWeight: '600' },
    priceTag: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
    priceText: { fontSize: 14, fontWeight: '800' },
    broadcastLocation: { fontSize: 13, color: COLORS.textSecondary, marginVertical: 12, fontWeight: '600' },
    acceptButton: { backgroundColor: COLORS.primary, paddingVertical: 12, borderRadius: 12, alignItems: 'center' },
    acceptButtonText: { color: '#fff', fontWeight: '800', fontSize: 14 },
    // Location Bottom Sheet
    bottomSheetContainer: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
      zIndex: 100000,
      elevation: 35,
    },
    bottomSheet: {
      backgroundColor: COLORS.card,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 24,
      minHeight: 580,
      maxHeight: '95%',
      ...getShadow('#000', 0, -4, 0.15, 16, 35),
      borderTopWidth: 1,
      borderTopColor: COLORS.border,
    },
    sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    sheetTitle: { fontSize: 20, fontWeight: '800', color: COLORS.textPrimary },
    sheetSubtitle: { fontSize: 13, color: COLORS.textSecondary, marginBottom: 16, fontWeight: '500' },
    countryBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.background,
      padding: 12,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      justifyContent: 'space-between',
      marginBottom: 16,
    },
    countryInfo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    countryText: { fontSize: 14, color: COLORS.textPrimary, fontWeight: '700' },
    countryChangeBtn: { fontSize: 12, color: COLORS.primary, fontWeight: '800' },
    sheetActionRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
    sheetActionButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: COLORS.background,
      paddingVertical: 14,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: COLORS.border,
      gap: 8,
    },
    sheetActionButtonText: { fontSize: 13, color: COLORS.textPrimary, fontWeight: '700' },
    addressItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: COLORS.border,
      justifyContent: 'space-between',
    },
    addressItemLeft: { flexDirection: 'row', alignItems: 'center', flex: 1, marginRight: 12, gap: 12 },
    addressIconWrapper: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: COLORS.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    addressItemLabel: { fontSize: 14, color: COLORS.textPrimary, fontWeight: '700' },
    addressItemText: { fontSize: 12, color: COLORS.textSecondary, fontWeight: '500', marginTop: 2 },
    addressActions: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    mapSearchWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: COLORS.background,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 52,
      marginBottom: 16,
    },
    mapSearchInput: { flex: 1, color: COLORS.textPrimary, fontSize: 14, fontWeight: '600', marginLeft: 10, padding: 0 },
    mapContainer: {
      height: 260,
      borderRadius: 20,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: COLORS.border,
      position: 'relative',
      marginBottom: 16,
    },
    mapFloatingBtn: {
      position: 'absolute',
      bottom: 16,
      right: 16,
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: COLORS.card,
      alignItems: 'center',
      justifyContent: 'center',
      ...getShadow('#000', 0, 2, 0.15, 4, 4),
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    addressNote: { fontSize: 12, color: COLORS.textSecondary, fontWeight: '600', textAlign: 'center', marginBottom: 20, lineHeight: 18 },
    labelRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginBottom: 20 },
    labelBadge: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: COLORS.background,
      borderWidth: 1,
      borderColor: COLORS.border,
    },
    labelBadgeActive: { backgroundColor: COLORS.primary + '15', borderColor: COLORS.primary },
    labelBadgeText: { fontSize: 12, fontWeight: '700', color: COLORS.textSecondary },
    labelBadgeTextActive: { color: COLORS.primary },
    formInputWrapper: {
      backgroundColor: COLORS.background,
      borderWidth: 1,
      borderColor: COLORS.border,
      borderRadius: 16,
      paddingHorizontal: 16,
      height: 52,
      justifyContent: 'center',
      marginBottom: 16,
    },
    formTextInput: { color: COLORS.textPrimary, fontSize: 14, fontWeight: '600', padding: 0 },
  });
